compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: <YOURIP>
main_process_port: 4321
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 16
use_cpu: false
